version: '3.3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    ports:
      - 3001:3001
    restart: always
    volumes:
      - ./:/server
volumes:
  node_modules:
